# version: "3.8"

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./server
    container_name: go-backend
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    environment:
      - DB_URI=mongodb://root:password@mongodb:27017 # Use the correct MongoDB port
      - DB_NAME=test
      - DB_COLLECTION_NAME=todolist

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: react-frontend
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_ENDPOINT=${REACT_APP_API_ENDPOINT}

volumes:
  mongo-data:
